<?php
$selected_roles = get_post_meta( $post->ID, 'wp_role_specific_content__role', true );
$message = get_post_meta( $post->ID, 'wp_role_specific_content__message', true );
$redirect = get_post_meta( $post->ID, 'wp_role_specific_content__redirect', true );
?>
<p>
    <label class="post-attributes-label">
        <strong>Select which Roles to show content too:</strong>
    </label><br />
    <?php
    foreach( self::getUserRoles() as $user_role ) {
        $lowercase = strtolower( $user_role );
        ?>
        <label for="wp_role_specific_content__<?php echo $lowercase; ?>">
            <input 
                type="checkbox" 
                name="wp_role_specific_content__role[]" 
                id="wp_role_specific_content__<?php echo $lowercase; ?>" 
                value="<?php echo $lowercase; ?>"
                <?php echo ( in_array( $lowercase, $selected_roles ) ) ? ' checked="checked"' : ''; ?>  /> 
            <?php echo $user_role; ?>
        </label><br />
        <?php
    }
    ?>
    <span class="description">By not choosing a role, the post will be public.</span>
</p>
<p>
    <label for="wp_role_specific_content__message">
        <strong>Message to display to restricted roles:</strong>
    </label><br />
    <textarea 
        class="large-text" 
        name="wp_role_specific_content__message" 
        id="wp_role_specific_content__message" 
        rows="4">
        <?php echo $message; ?>
    </textarea>
</p>
<p>
    <label for="wp_role_specific_content__redirect">
        <strong>Redirect restricted roles to:</strong>
    </label><br />
    <input 
        type="text" 
        class="large-text" 
        name="wp_role_specific_content__redirect" 
        id="wp_role_specific_content__redirect" 
        value="<?php echo $redirect; ?>" />
</p>
<!-- WP Nonce (Very Important - DO NOT REMOVE) -->
<?php wp_nonce_field( self::NONCE_ACTION, self::NONCE_NAME ); ?>
<!-- WP Nonce (end) -->